# Generated by Django 3.0.5 on 2020-04-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_attempt_user_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_answer',
            old_name='solution',
            new_name='attempt',
        ),
    ]
