# Generated by Django 3.0.5 on 2020-05-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_attemptquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
