# Generated by Django 3.0.5 on 2020-06-06 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0007_quiz_is_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_opponent', to=settings.AUTH_USER_MODEL),
        ),
    ]
