# Generated by Django 3.0.5 on 2020-06-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_attempt_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='author_answered1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='opponent_answered2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_answer',
            name='opponent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
