# Generated by Django 3.0.5 on 2020-06-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200606_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attemptquestion',
            old_name='author_answered1',
            new_name='author_answered',
        ),
        migrations.RenameField(
            model_name='attemptquestion',
            old_name='opponent_answered2',
            new_name='opponent_answered',
        ),
    ]
