# Generated by Django 3.0.5 on 2020-05-21 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_side_text', models.TextField(max_length=1000)),
                ('front_side_img', models.ImageField(upload_to='flash_cards_images')),
                ('back_side_text', models.TextField(max_length=1000)),
                ('back_side_img', models.ImageField(upload_to='flash_cards_images')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlashCards.Subject')),
            ],
        ),
    ]
