# Generated by Django 3.0.5 on 2020-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashCards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='marked_as_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='back_side_img',
            field=models.ImageField(blank=True, upload_to='flash_cards_images'),
        ),
        migrations.AlterField(
            model_name='card',
            name='back_side_text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='front_side_img',
            field=models.ImageField(blank=True, upload_to='flash_cards_images'),
        ),
        migrations.AlterField(
            model_name='card',
            name='front_side_text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
