# Generated by Django 3.0.5 on 2020-05-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashCards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back_side_img',
            field=models.ImageField(blank=True, upload_to='flash_cards_images'),
        ),
        migrations.AlterField(
            model_name='card',
            name='back_side_text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='front_side_img',
            field=models.ImageField(blank=True, upload_to='flash_cards_images'),
        ),
        migrations.AlterField(
            model_name='card',
            name='front_side_text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
