# Generated by Django 3.0.5 on 2020-05-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashCards', '0002_auto_20200521_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='marked_as_known',
            field=models.BooleanField(default=False),
        ),
    ]
