# Generated by Django 3.0.5 on 2020-05-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashCards', '0003_card_marked_as_known'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back_side_text',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='front_side_text',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
    ]
